module.exports = {
  getBank: {
    url: "/index.php/api/getBank",
    input: {},
    result: { id: "1", bank: "Maybank", status: "1" },
  },
  getBankFPX: {
    url: "/index.php/api/getBankFPX",
    input: {},
    result: { CODE: "ABB0233", NAME: "Affin Bank" },
  },
  getPackage: {
    url: "/index.php/api/getPackage",
    input: {},
    result: { id: "1", package: "Pakej Standard", fee: "0.30", status: "1" },
  },
  createCategory: {
    url: "/index.php/api/createCategory",
    input: {},
    result: { CategoryCode: "j0tzqhka" },
  },
  getCategoryDetails: {
    url: "/index.php/api/getCategoryDetails",
    input: {},
    result: {
      categoryName: "Makanan",
      categoryDescription: "Kuih Cara",
      categoryStatus: "1",
    },
  },
  createBill: {
    url: "/index.php/api/createBill",
    input: {
      userSecretKey: "",
      categoryCode: "",
      billName: "",
      billDescription: "",
      billPriceSetting: "",
      billPayorInfo: "",
      billAmount: "",
      billReturnUrl: "",
      billCallbackUrl: "",
      billExternalReferenceNo: "",
      billTo: "",
      billEmail: "",
      billPhone: "",
      billSplitPayment: { optional: true },
      billSplitPaymentArgs: { optional: true },
      billPaymentChannel: "",
      billDisplayMerchant: { optional: true },
      billContentEmail: { optional: true },
      billAdditionalField: { optional: true },
      billChargeToCustomer: "",
    },
    result: { BillCode: "gcbhict9" },
  },
  createBillMultiPayment: {
    url: "/index.php/api/createBillMultiPayment",
    input: {
      userSecretKey: "",
      categoryCode: "",
      billName: "",
      billDescription: "",
      billPriceSetting: "",
      billPayorInfo: "",
      billAmount: "",
      billReturnUrl: "",
      billCallbackUrl: "",
      billExternalReferenceNo: "",
      billTo: "",
      billEmail: "",
      billPhone: "",
      billSplitPayment: "",
      billSplitPaymentArgs: "",
      billMultiPayment: "",
      billPaymentChannel: { optional: true },
      billDisplayMerchant: { optional: true },
      billContentEmail: { optional: true },
    },
    result: { BillCode: "j0tzqhka" },
  },
  runBill: {
    url: "/index.php/api/runBill",
    input: {
      userSecretKey: "",
      billCode: "",
      billpaymentAmount: { optional: true },
      billpaymentPayorName: "",
      billpaymentPayorPhone: "",
      billpaymentPayorEmail: "",
      billBankID: { optional: true },
    },
    result: {},
  },
  getBillTransactions: {
    url: "/index.php/api/getBillTransactions",
    input: {},
    result: {
      billName: "Payment_for_order_51",
      billDescription: "Payment_for_order_51",
      billTo: "",
      billEmail: "",
      billPhone: "",
      billStatus: "1",
      billPermalink: "zyq1pq6s",
      categoryCode: "vkptzhxe",
      categoryName: "Wordpress",
      userName: "fitweb",
      billpaymentStatus: "3",
      billpaymentAmount: "1.00",
      billpaymentInvoiceNo: "B00040-288-424703111018",
    },
  }, // partnerType
  getAllBill: {
    url: "/admin/api/getAllBill",
    input: {
      userSecretKey: "",
      partnerType: "",
      "Year-month": "",
    },
    result: {
      billDate: "2018-10-11",
      ID: "39",
      NAME: "Kuih Cara Meletop",
      billDescription: "Kutipan pakej Kuih Cara meletop",
      fixPrice: "Not fix",
      billTo: "",
      billEmail: "",
      billPhone: "",
      billStatus: " (Not Active)",
      billCode: "kuih-cara-meletop",
      billAmount: "1.00",
      categoryCode: "tsrbklhf",
      categoryName: "Makanan",
      userName: "fitweb",
    },
  }, // enterprise
  createAccount: {
    url: "/index.php/api/createAccount",
    input: {
      Fullname: "",
      User: "",
      Email: "",
      Password: "",
      Phone: "",
      Bank: "",
      Account: "",
      Account: "",
      Registration: "",
      Package: "",
      Following: "",
    },
    result: { UserSecretKey: "vrbl86xf-wj1h-q0l3-95kk-4q4erulvsc0h" },
  }, // enterprise
  getUserStatus: {
    url: "/index.php/api/getUserStatus",
    input: {},
    result: { status: "1" },
  }, // hybrid
  getAllUser: {
    url: "/admin/api/getAllUser",
    input: { userSecretKey: "", partnerType: "" },
    result: {
      userDate: "2018-10-11",
      userId: "45",
      userName: "zahiruliman",
      registrationNo: "XXXXXXXXXXX",
      userFullname: "Mohd Zahirul Iman bin Mohammad Rafee",
      userEmail: "zahirul.imn@gmail.com",
      userPhone: "0182500999",
      BankAccountNo: "155444478239",
      bankAccountName: "Mohd Zahirul Iman",
      bankName: "Maybank",
      userStatus: " (Not Active)",
    },
  }, // partnerType
  getSettlement: {
    url: "/admin/api/getSettlement",
    input: {
      userSecretKey: "",
      partnerType: "",
      detailByuserName: "",
    },
    result: {
      userID: "44",
      userName: "fitweb",
      settlementDate: "2019-10-28",
      amount: "1.00",
      amountNett: "1.00",
      different: "0.00",
      standard: "0.00",
      santai: "1.00",
      creditCard: "0.00",
      transaction: "1",
    },
  }, // partnerType
  getSettlementSummary: {
    url: "/admin/api/getSettlementSummary",
    input: {
      userSecretKey: "",
      userPartnerType: "",
      userName: "",
    },
    result: {
      userID: "44",
      userName: "fitweb",
      today: "19-10-31",
      Amount_Pending: "1.00",
      Amount_settle: "5.00",
      AmountNett_Pending: "1.00",
      AmountNett_Settle: "0.00",
      Different_Pending: "0.00",
      Different_Settle: "5.00",
      Standard_Pending: "0.00",
      Standard_Settle: "0.00",
      Santai_Pending: "1.00",
      Santai_Settle: "5.00",
      Creditcard_Pending: "0.00",
      Creditcard_settle: "0.00",
      Transaction_Pending: "6",
      Trnsaction_Settle: "6",
    },
  },
};
